### ISSUE TITLE
Ignore path is relative to currently open file and not .vale.ini

### ISSUE THREAD

**Issue by pwalleni** [errata-ai/vale-vscode#114]
Given the following dictionary rule:

```plaintext
extends: spelling
message: "Did you really mean '%s'?"
level: error
ignore:
  - .vale/developer-style-guide/styles/Vocab/Base/accept.txt
```

And the following repository layout:

```plaintext
repo
├── .vale
│   └── developer-style-guide
│       └── styles
│           └── Vocab
│               └── Base
│                   ├── accept.txt
│                   └── reject.tx
├── .vale.ini
├── readme.md
└── docs
    └── index.md
```

Linting works as expected when opening `readme.md`. But when opening `docs/index.md`, the extension errors out with the following message in the Output pane in VS Code:

```plaintext
open /Users/<username>/src/repo/docs/.vale/developer-style-guide/styles/Vocab/Base/accept.txt: no such file or directory
```

**Comment by jdkato** [comment]
There are two problems here.

Ignore files are relative to the `StylesPath`, not `.vale.ini`. So this will work:

```yaml
extends: spelling
message: "Did you really mean '%s'?"
level: error
ignore:
  - Vocab/Base/accept.txt
```

But this is a misuse of the `Vocab` feature which (unlike ignore files) is intended to be used independent of any one style. The following is the correct way to use an `accept.txt` file:

```ini
StylesPath = .vale/<...>

Vocab = Base

[*]
# Other config ...
```

and

```yaml
# You could also just use `Vale.Spelling`.
extends: spelling
message: "Did you really mean '%s'?"
level: error
```
